=== mmyumu/TroncGame/android/assets/data/characters.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="characters">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" ref="character"></xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="character">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="attack"></xsd:element>
                <xsd:element ref="actionSpeed"></xsd:element>
                <xsd:element ref="hp"></xsd:element>
                <xsd:element ref="mp"></xsd:element>
                <xsd:element ref="fight" minOccurs="0"></xsd:element>
                <xsd:element ref="overworld" minOccurs="0"></xsd:element>
            </xsd:sequence>
            <xsd:attribute ref="id"></xsd:attribute>
            <xsd:attribute ref="name"></xsd:attribute>
            <xsd:attribute ref="friendly"></xsd:attribute>
            <xsd:attribute ref="usingAI"></xsd:attribute>
            <xsd:attribute ref="playable"></xsd:attribute>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="fight">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="waitingTexture"></xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="overworld">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="topTexture"></xsd:element>
                <xsd:element ref="bottomTexture"></xsd:element>
                <xsd:element ref="leftTexture"></xsd:element>
                <xsd:element ref="rightTexture"></xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="waitingTexture" type="xsd:string"></xsd:element>

    <xsd:element name="topTexture" type="xsd:string"></xsd:element>
    <xsd:element name="bottomTexture" type="xsd:string"></xsd:element>
    <xsd:element name="leftTexture" type="xsd:string"></xsd:element>
    <xsd:element name="rightTexture" type="xsd:string"></xsd:element>

    <xsd:element name="attack" type="xsd:int"></xsd:element>
    <xsd:element name="actionSpeed" type="xsd:int"></xsd:element>
    <xsd:element name="hp" type="xsd:int"></xsd:element>
    <xsd:element name="mp" type="xsd:int"></xsd:element>

    <xsd:attribute name="id" type="xsd:ID"></xsd:attribute>
    <xsd:attribute name="name" type="xsd:string"></xsd:attribute>
    <xsd:attribute name="friendly" type="xsd:boolean" default="false"></xsd:attribute>
    <xsd:attribute name="usingAI" type="xsd:boolean" default="false"></xsd:attribute>
    <xsd:attribute name="playable" type="xsd:boolean" default="false"></xsd:attribute>
</xsd:schema>

=== mmyumu/TroncGame/core/test/resources/characters.xml
<?xml version="1.0"?>
<characters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="characters.xsd">
    <character id="main" name="Daia" friendly="true" playable="true">
        <attack>8</attack>
        <actionSpeed>40</actionSpeed>
        <hp>118</hp>
        <mp>72</mp>
        <fight>
            <waitingTexture>data/fight/heroine_droite.png</waitingTexture>
        </fight>
        <overworld>
            <topTexture>data/overworld/heroine_dos.png</topTexture>
            <bottomTexture>data/overworld/heroine_face.png</bottomTexture>
            <leftTexture>data/overworld/heroine_gauche.png</leftTexture>
            <rightTexture>data/overworld/heroine_droite.png</rightTexture>
        </overworld>
    </character>
    <character id="sideKick" name="Neykallo" friendly="true" playable="true">
        <attack>9</attack>
        <actionSpeed>30</actionSpeed>
        <hp>131</hp>
        <mp>61</mp>
        <fight>
            <waitingTexture>data/fight/compagnon_droite.png</waitingTexture>
        </fight>
    </character>
    <character id="soldier" name="Soldier" usingAI="true">
        <attack>9</attack>
        <actionSpeed>35</actionSpeed>
        <hp>20</hp>
        <mp>10</mp>
        <fight>
            <waitingTexture>data/fight/ennemi_gauche.png</waitingTexture>
        </fight>
    </character>
    <character id="bestFriend" name="Mirena" usingAI="true">
        <attack>1</attack>
        <actionSpeed>10</actionSpeed>
        <hp>10</hp>
        <mp>10</mp>
    </character>
</characters>
